### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#351]
my dust:
{>"layouts/master"/}

{<body}
<div id="wrap">
       <div class="section" id="score-home">
                   <div id="score-point">
                       <div class="cont">
                           <h1></h1><span></span>
                       </div>
                   </div>
                   <p>{@pre type="content" key="topicshare.description"/}</p>
               </div>

       </div>
{/body}

error:
language：zh-CN,zh;q=0.8
Thu, 19 Mar 2015 09:29:28 GMT uncaughtException Cannot find module './'
Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports._getLibForType (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/node_modules/spud/lib/serializer/serializerFactory.js:32:32)
    at Object.module.exports.buildDeserializer (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/node_modules/spud/lib/serializer/serializerFactory.js:38:20)
    at deserialize (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/node_modules/spud/lib/transcoder.js:121:42)
    at Object.startDeserialize [as deserialize] (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/node_modules/spud/lib/transcoder.js:163:5)
    at Object.prototype.load (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/lib/bundle.js:65:14)
    at Object.handler.onTag (/Users/whw/code/Server-API2/node_modules/engine-munger/node_modules/localizr/lib/handler.js:49:21)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/6727618/504c54d8-ce5e-11e4-8879-fb81ebaa4336.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/6727741/5369d8ba-ce5f-11e4-8ea8-97dcf6ba165a.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/6728243/79fd14b6-ce63-11e4-8b29-97761c166c3a.png)

**Comment by chelsh** [comment]
what is the 'type' of bundle object ,why it is blank?
![image](https://cloud.githubusercontent.com/assets/10752360/6728646/34469804-ce66-11e4-9bc0-43209fec7957.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/6728967/2e57d2f2-ce69-11e4-944a-8153914c9f9d.png)
![image](https://cloud.githubusercontent.com/assets/10752360/6728987/536078e2-ce69-11e4-862e-7d974187da6b.png)
when i use score.js,it is ok,but return:sever error 
![image](https://cloud.githubusercontent.com/assets/10752360/6729024/7f4070ca-ce69-11e4-9efd-a9d8a52e69f5.png)

**Comment by chelsh** [comment]
how to config the config.json and development.json to support locale?:)

**Comment by chelsh** [comment]
_getLibForType: function (type) {
		var clazz = this._cache[type];
		if (!clazz) {
			clazz = this._cache[type] = require('./' + type);
		}
		return clazz;
	},


type is blank,so Error: Cannot find module './',what is the type

**Comment by chelsh** [comment]
it is OK now.the name of the dust document must be the same as the name of the properties document.:)

**Comment by aredridel** [comment]
Yep! I'm working on changing that in `adaro@2`.

Error message could be improved though!
