### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ChitaGideon** [krakenjs/kraken-js#371]
sometimes ,we can get this error below ,when server response some POST request.
but we can not catch this error in development env

```
...
# at View.proto.render (/node_modules/engine-munger/lib/expressView.js:45:9)
# at engine (/node_modules/adaro/lib/engine.js:92:15)
# at Object.apply (/node_modules/adaro/lib/patch/index.js:113:13)
# at notApplied (/node_modules/adaro/lib/patch/index.js:126:13)
# at applied (/node_modules/adaro/lib/patch/index.js:121:21)
#TypeError: Cannot read property 'name' of undefined
```
I  do not have any clue about this.
 would someone show me some hint or or any possible case that error may happen?

**Comment by lmarkus** [comment]
You may need to run a `grunt build` before starting up your server.

**Comment by pvenkatakrishnan** [comment]
The stack trace indicates that you are running your app in production mode which expects the templates to be compiled ahead of time (i presume you are using dust ?) So like @lmarkus mentioned, if you run `grunt build`,  it compiles the templates.
But if you are already doing this, you probably want to check if you have `.properties` in all the locales that you expect your dust partials to me localized in.

**Comment by wyvernnot** [comment]
I ran into the same problem, it is related to following commit during dustjs@2.6.2 to dustjs@2.7
https://github.com/linkedin/dustjs/commit/885d7e21af3d284c6f97a67901d08c8ee8f5956e

the `dust.load` function seems to be removed in dustjs@2.7

But adaro@0.1.8, obviously depends on the existence of `dust.load`
see line number https://github.com/krakenjs/adaro/blob/v0.1.8/lib/patch/index.js#L121

specify the one before latest version would work for the moment
```
dependencies: {
...
"dustjs-helpers": "1.6.3",
"dustjs-linkedin": "2.6.2", 
}
``

**Comment by ChitaGideon** [comment]
@lmarkus @pvenkatakrishnan  I can make sure I have already run grunt build before start.
@pvenkatakrishnan The advise that checking the .properties is really inspire on me ,but it is still not the real problem for me after check.
@wyvernnot I will try to change dustjs version ,maybe this can be worked

**Comment by ChocoboMaster** [comment]
@wyvernnot Thanks for pointing this out. Everything working fine with dustjs@2.6.2

**Comment by aredridel** [comment]
Yeah. Working on fixes!

**Comment by jasisk** [comment]
Closing due to inactivity. Feel free to continue the discussion if issues persist.
