### ISSUE TITLE
server error Error: request aborted

### ISSUE THREAD

**Issue by tomalex0** [krakenjs/kraken-js#401]
I came across  error in my app, but couldn't figure where it is going wrong. Can anybody help me explain what is the issue

```
server error Error: request aborted
    at makeError (/myapp/node_modules/kraken-js/node_modules/body-parser/node_modules/raw-body/index.js:156:15)
    at IncomingMessage.onAborted (/myapp/node_modules/kraken-js/node_modules/body-parser/node_modules/raw-body/index.js:254:10)
    at IncomingMessage.emit (events.js:92:17)
    at abortIncoming (http.js:1911:11)
    at Socket.serverSocketCloseListener (http.js:1923:5)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:465:12)
```

I came across similar post here https://github.com/expressjs/body-parser/issues/112

**Comment by aredridel** [comment]
Sounds like your browser stopped mid-stream -- perhaps navigating away during the sending of the request.

**Comment by tomalex0** [comment]
Is there  a way to handle this,  looks like this can cause error 500 and stop the server if we are not using `forever` or `supervisor.`

Is there a specific steps to reproduce.

**Comment by aredridel** [comment]
reproducing it can be a bit hard since you have to abort a connection from a client -- it may be possible to simulate, but ow.

Sounds like the error handling in the body-parser module is missing one state.

**Comment by aredridel** [comment]
I'm looking deeper here -- this is truly fatal? Not emitted into the middleware chain

**Comment by tomalex0** [comment]
I see these consoles from `\myapp\node_modules\kraken-js\middleware\500.js`.

**Comment by aredridel** [comment]
If they get logged from the error-handling middleware, they shouldn't crash your process.

Also: you disable the 500 middleware and get Express's, which is better. The internal one is being disabled by default in kraken 2.0

**Comment by trideepgogoi** [comment]
I have seen this when an up stream ajax request times out. Its also likely you made a request just before the page navigated away both of which will cause the Browser to abandon the request.

**Comment by tomalex0** [comment]
Thanks for the  inputs.

**Comment by jasisk** [comment]
Closing due to inactivity.
