### ISSUE TITLE
unexpected reserved word

### ISSUE THREAD

**Issue by jknight12882** [krakenjs/kraken-js#425]
with kraken 2.0.0 on node 4.1.0

    /home/vagrant/xxx/node-client/node_modules/kraken-js/node_modules/confit/index.js:16
    import Path from 'path';
    ^^^^^^
    
    SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/xxxx/node-client/node_modules/kraken-js/lib/config.js:22:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/xxxx/node-client/node_modules/kraken-js/lib/settings.js:21:14)
    at Module._compile (module.js:434:26)

**Comment by jasisk** [comment]
Well that's strange. The `package.json` has `dist/index.js` and the `main`, which is built `prepublish` (I confirmed it's in the tarball too).

I'm unable to reproduce with both npm ^2 and ^3. Any other info you can provide to help reproduce? Anything atypical about how you installed your dependencies?

**Comment by jknight12882** [comment]
Strange, nuked my node_modules dir and reinstalled, seemed to fix the behavior.

**Comment by jasisk** [comment]
My favorite type of issue! :grinning: 
Glad it resolved itself.
