### ISSUE TITLE
dust.render without using response context does not work.

### ISSUE THREAD

**Issue by killfish** [krakenjs/kraken-js#448]
res.render works as a expected but I need to render an email template and that component does not have access to res as it's part of a cron job.

I required dust like so: `var dust = require('dustjs-linkedin');`

But when I try to render I get the following error.

```
error: err sending email TypeError: context.get is not a function
    at onLoad (/Volumes/Data/WebstormProjects/tamarin/node_modules/engine-munger/view/dust.js:41:26)
    at Object.spclOnLoad [as onLoad] (/Volumes/Data/WebstormProjects/tamarin/node_modules/engine-munger/lib/munger.js:75:9)
    at /Volumes/Data/WebstormProjects/tamarin/node_modules/dustjs-linkedin/lib/dust.js:144:16
    at Chunk.map (/Volumes/Data/WebstormProjects/tamarin/node_modules/dustjs-linkedin/lib/dust.js:583:7)
    at Object.dust.load [as __cabbage__] (/Volumes/Data/WebstormProjects/tamarin/node_modules/dustjs-linkedin/lib/dust.js:143:22)
    at Object.cabbage [as load] (/Volumes/Data/WebstormProjects/tamarin/node_modules/adaro/lib/patch/index.js:102:21)
    at Object.dust.render (/Volumes/Data/WebstormProjects/tamarin/node_modules/dustjs-linkedin/lib/dust.js:95:12)
    at Object.sendEmail (/Volumes/Data/WebstormProjects/tamarin/lib/mandrill.js:54:12)
    at /Volumes/Data/WebstormProjects/tamarin/controllers/admin/forgot-password/index.js:62:16
    at processImmediate [as _immediateCallback] (timers.js:371:17)
From previous event:
    at /Volumes/Data/WebstormProjects/tamarin/controllers/admin/forgot-password/index.js:60:8
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:131:13)
    at /Volumes/Data/WebstormProjects/tamarin/lib/flash-service.js:27:5
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:131:13)
    at /Volumes/Data/WebstormProjects/tamarin/lib/policies/refreshSessionCookie.js:9:12
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:131:13)
    at /Volumes/Data/WebstormProjects/tamarin/lib/flash-service.js:27:5
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:131:13)
    at /Volumes/Data/WebstormProjects/tamarin/lib/policies/refreshSessionCookie.js:9:12
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at /Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:330:12)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:176:3)
    at router (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:312:13)
    at /Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:330:12)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:176:3)
    at router (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:312:13)
    at /Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:330:12)
    at next (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/index.js:271:10)
    at lusca (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/lusca/index.js:53:9)
    at lusca (eval at createToggleWrapper (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/meddleware/index.js:133:51), <anonymous>:1:66)
    at Layer.handle [as handle_request] (/Volumes/Data/WebstormProjects/tamarin/node_modules/express/lib/router/layer.js:95:5)
```

Any ideas?

I'm using dustjs-linkedin@2.6.1

**Comment by grawk** [comment]
Within the process where the kraken app is running, engine-munger overrides `dust.onLoad`. If you want to use dust outside of the res context, you can load a fresh version of `dustjs-linkedin` in the module where you want to use it.

You can use [freshy](https://www.npmjs.com/package/freshy) to do that.

**Comment by grawk** [comment]
close due to inactivity
