### ISSUE TITLE
Error page (404.js)  not rendering in production mode 

### ISSUE THREAD

**Issue by muguatnus** [krakenjs/kraken-js#453]
Hi 
I am using following versions on my application

> "kraken-js": "0.7.5"
> "adaro": "0.1.7"

When I run the application in development mode it is redirecting 404 page. But in the production mode it is not happening. It is throwing following error.

```
500 Error: Could not load template
   at Object.onLoad (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\makara\lib\view\js.js:84:22)
   at Object.cache.get (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\makara\lib\cache.js:61:14)
   at C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\adaro\lib\reader\file.js:62:16
   at onChunk (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\adaro\lib\patch\index.js:69:29)
   at Chunk.map (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\dustjs-linkedin\lib\dust.js:370:3)
   at C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\adaro\lib\patch\index.js:91:39
   at Object.dust.load [as __cabbage__] (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\dustjs-linkedin\lib\dust.js:51:12)
   at Object.cabbage [as load] (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\adaro\lib\patch\index.js:98:21)
   at Object.dust.render (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\dustjs-linkedin\lib\dust.js:22:8)
   at engine (C:\Mugu\Project\NI_74\mlp\mlp-webapp\node_modules\adaro\lib\engine.js:133:14)
```

When I dig the code I understood that 'views' become empty after this line of code
https://github.com/krakenjs/adaro/blob/v0.1.x/lib/engine.js#L99

This is only for error pages. For other application pages its is returning folder path **'.build\templates\GB\en\'**

Also in line 84
https://github.com/krakenjs/adaro/blob/v0.1.x/lib/engine.js#L84

value of **settings.views** in  Option argument coming as

> Normal pages - folder path
> Error page -file path

Please help me @jeffharrell @aredridel 

Thanks,
K.Mugunthan

**Comment by aredridel** [comment]
what version of dust are you using?

Those are really old versions ... I don't know what might be wrong offhand, and my first thought is 'please please please upgrade'

**Comment by muguatnus** [comment]
I am using "dustjs-linkedin": "2.0.3"

**Comment by aredridel** [comment]
Yeah, wow. So much has changed for the better since then. You could be hitting any number of bugs or misconfigurations. Which Express?

**Comment by muguatnus** [comment]
Express - 3.16.10.
I am not facing any other major issues.

**Comment by aredridel** [comment]
I think those versions work together but it's before my time in Kraken.

**Comment by muguatnus** [comment]
Thanks. I am unable to update the modules now. I want to dig more and find-out the issue.

Can you please give me a hint that which module will call this method ?

**Comment by aredridel** [comment]
express.

**Comment by muguatnus** [comment]
HI @aredridel 

It is working fine and error page is rendering in the production mode if I change this line as follows

https://github.com/krakenjs/makara/blob/v0.3.5/lib/util.js#L70

Change 
`root : file.replace(name, '')` to `root : file.replace(name.replace('/','\\'), '')`

But I cannot see the util.js file in latest makara versions. :(
