### ISSUE TITLE
Tests beforeEach not passing config.json to application options.

### ISSUE THREAD

**Issue by killfish** [krakenjs/kraken-js#459]
I have modules that require additional information from the configuration.json. When I run the application outside of the mocha tests everything runs fine, but if I run it through test runner the config argument is undefined. 

Sample Test:

```
'use strict';

var kraken = require('kraken-js');
var express = require('express');
var path = require('path');
var request = require('supertest');

describe('index', function () {

  var app, mock;

  beforeEach(function (done) {

    app = express();
    app.on('start', done);
    app.use(kraken(require('../lib/options')(app)));
    mock = app.listen(1337);

  });

  afterEach(function (done) {
    mock.close(done);
  });

  it('should say "hello"', function (done) {
    request(mock)
      .get('/')
      .expect(200)
      .expect('Content-Type', /html/)

      .expect(/Hello, /)

      .end(function (err, res) {
        done(err);
      });
  });

});
```

Error in console output:

```
Possibly unhandled TypeError: Cannot read property 'api_key' of undefined
    at Object.init (/Volumes/Data/WebstormProjects/tamarin/lib/mandrill.js:45:32)
    at onconfig (/Volumes/Data/WebstormProjects/tamarin/lib/options.js:22:34)
    at promisified (eval at makeNodePromisifiedEval (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/promisify.js:198:12), <anonymous>:3:213)
    at tryCatch1 (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/Volumes/Data/WebstormProjects/tamarin/node_modules/kraken-js/node_modules/bluebird/js/main/async.js:37:14)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    1) "before each" hook


  0 passing (6s)
  1 failing

  1) index "before each" hook:
     Error: timeout of 6000ms exceeded. Ensure the done() callback is being called in this test.
```

options.js

```
'use strict';

var crypto = require('./crypto');
var db = require('./database');
var prodHooks = require('./productionHooks');

module.exports = function options(app) {

  return {
    onconfig: function (config, next) {
      ...
      require('../lib/mandrill').init(config.get('mandrill'));
      ...
      });
    },
  };
};
```

Mandrill.js

```
var Mandrill = function () {
...
  return {

    init: function (config) {
      MANDRILL_API_KEY = config.api_key;
      MANDRILL_FROM_ADDRESS = config.from_address;
      MANDRILL_FROM_NAME = config.from_name;
      MANDRILL_CLIENT = new mandrill.Mandrill(MANDRILL_API_KEY);
    },
...
  };
};
```

Any ideas?

**Comment by jasisk** [comment]
Yup! You need to set your `basedir` appropriately.

``` js
var kraken = require('kraken-js');
var express = require('express');
var path = require('path');

// assuming your tests are in `./test`, you just need to point `basedir` up one folder:
var basedir = path.resolve(__dirname, '..');

var app = express();

app.use(kraken({
  basedir: basedir // <-- this is where we actually set the basedir
}));
```

**Comment by grawk** [comment]
answered
