### ISSUE TITLE
Getting properties from kraken config before passing it to server doesn't seem to be working

### ISSUE THREAD

**Issue by osukaa** [krakenjs/kraken-js#466]
I'm trying to place port configuration on the config.json file but I'm not able to retrieve it. I'm following this issue https://github.com/krakenjs/kraken-js/issues/385 but it doesn't appear to work

``` javascript
//index.js
'use strict';

const express = require('express');
const kraken = require('kraken-js');

/*
 * Create and configure application. Also exports application instance for use by tests.
 * See https://github.com/krakenjs/kraken-js#options for additional configuration options.
 */
const options = {
  onconfig: function onconfig(config, next) {
  /*
   * Add any additional config setup or overrides here. `config` is an initialized
   * `confit` (https://github.com/krakenjs/confit/) configuration object.
   */
    next(null, config);
  },
};

const app = module.exports = express();
app.use(kraken(options));
app.on('start', () => {
  console.log('Application ready to serve requests.'); //eslint-disable-line
  console.log('Environment: %s', app.kraken.get('env:env')); //eslint-disable-line
});


//server.js
const app = require('./index');
const http = require('http');

/*
 * Create and start HTTP server.
 */

const server = http.createServer(app);
server.listen(app.kraken.get('service:port'));
server.on('listening', function listening() {
  console.log('Server listening on http://localhost:%d', this.address().port); //eslint-disable-line
});

//config.json
{
    "service": {
      "port": "8000"
    },
    "middleware": {
        "router": {
            "module": {
                "arguments": [{ "directory": "path:./controllers" }]
            }
        }
    }
}

//development.json
{
  "service": {
    "port": "8080"
  }
}
```

and it throws this error

``` bash
Fri, 17 Jun 2016 23:33:40 GMT uncaughtException Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at Object.<anonymous> (/Users/ofunes/r/wizard-template-node-webapp/app/server.js:35:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by subeeshcbabu** [comment]
`server.listen(app.kraken.get('service:port'));` This line tries to use the `app.kraken` way too early. At this point (before configuration) the `app.kraken` is not available to be used.

**Comment by jonathansamines** [comment]
Hey @osukaa what about calling `app.listen` on the `start` kraken event instead? At that point, the app configuration should have been already resolved (See: https://github.com/krakenjs/kraken-js/blob/v2.x/index.js#L67, https://github.com/krakenjs/kraken-js/blob/v2.x/lib/settings.js#L120)
