### ISSUE TITLE
Creating New Project using yo for Ubuntu 16.04

### ISSUE THREAD

**Issue by egenedy97** [krakenjs/kraken-js#509]
@aredridel  I have the same issue while I am creating a new project with "yo kraken" . I use Ubuntu 16.04 and I use "sudo npm install -g yo generator-kraken bower grunt-cli " and already installed . but when I create a project it gave me this error:
/usr/lib/node_modules/generator-kraken/node_modules/configstore/index.js:56
				throw err;
				^

Error: EACCES: permission denied, open '/home/genedy/.config/configstore/update-notifier-generator-kraken.yml'
You don't have access to this file.

    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at Configstore.get (/usr/lib/node_modules/generator-kraken/node_modules/configstore/index.js:34:29)
    at new Configstore (/usr/lib/node_modules/generator-kraken/node_modules/configstore/index.js:27:45)
    at new UpdateNotifier (/usr/lib/node_modules/generator-kraken/node_modules/update-notifier/index.js:33:17)
    at module.exports (/usr/lib/node_modules/generator-kraken/node_modules/update-notifier/index.js:126:23)
    at Object.update (/usr/lib/node_modules/generator-kraken/util/update.js:25:20)
    at Object.<anonymous> (/usr/lib/node_modules/generator-kraken/app/index.js:28:12)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)

_Originally posted by @genedy377 in https://github.com/krakenjs/kraken-js/issues/188#issuecomment-450533780_

**Comment by grawk** [comment]
Hi @yasir-rafiq. Apologies that nobody answered this yet. We are setting up a triage process very soon to address new issues on this repository going forward.

The generator software has not been touched in a long while. It may be incompatible with your environment for any number of reasons. I apologize that I can't offer an estimate of when or even if we will be supporting the generator again.

**Comment by kumarrishav** [comment]
Is it still valid? can we close it? @genedy377

**Comment by immaculatesoftsolutions** [comment]
While creating new project with command of `yo kraken` its showing below error

```
0h00m00s 0/0: : fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/usr/lib/node_modules/generator-kraken/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/lib/node_modules/generator-kraken/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/lib/node_modules/generator-kraken/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by kumarrishav** [comment]
hmm. I haven't reproduced it yet but you can also clone this repository and make required changes to set up the project (which is what yo does here)

**Comment by Trevahok** [comment]
I had the same issue, it is because kraken-generator is outdated and archived. i was on node 13.8, 
running `sudo n 11.15.0` made it work. Any way to update tutorials and kraken-generator ? shall i work on it ?

**Comment by i5on9i** [comment]
this issue may be related to this SO issue 

- https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
