### ISSUE TITLE
Yo Kraken Error

### ISSUE THREAD

**Issue by jordanfokoua** [krakenjs/kraken-js#521]
I installed Kraken Js to my windows computer and tried creating a new project but received this error: 
`ReferenceError: primordials is not defined at fs.js:35:5`

**Comment by Truth1984** [comment]
same with ubuntu 16.04

![image](https://user-images.githubusercontent.com/36292372/79527009-2659ea80-8099-11ea-9723-b08b8278de47.png)

**Comment by nfers** [comment]
I installed Kraken Js to my windows computer and tried creating a new project but received this error:
ReferenceError: primordials is not defined at fs.js:35:5

**Comment by marcosvaz** [comment]
I have the same issue, running in MacOS:
Error kraken

primordials is not defined

**Comment by sixlettervariables** [comment]
Which version of NodeJS? I ran into this issue with Gulp v3 on Node v12 and downgraded to v10 to fix it.

**Comment by jerp86** [comment]
I have the same issue, running in Ubuntu 18.04.4:
```batch
Error kraken

primordials is not defined
```

You mean I need to go back in time / downgrade my node.js so that lib works?

**Comment by sixlettervariables** [comment]
Or pin graceful-fs to a version which works with your NodeJS version. I believe the issue is due to monkey patching nodes fs lib and that no longer working.

**Comment by marcosvaz** [comment]
I imagine that it should be tidied up in the library and not be done a downgrade or something, because everyone who tries to use that library, will get that error.

**Comment by i5on9i** [comment]
Looks duplicate, see #509

**Comment by luisiceberg9** [comment]
Determining your Node version

node -v  // or node --version
npm -v   // npm version or long npm --version
Ensure that you have n installed

sudo npm install -g n // -g for global installation 
Upgrading to the latest stable version

sudo n stable
Changing to a specific version

sudo n 10.24.0
